# Generated by Django 5.2.17 on 2026-08-12 18:48

import apps.merchants.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_code', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=160)),
                ('legal_form', models.CharField(blank=True, max_length=80)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(default='BI', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('mcc', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_kyb', 'Pending KYB'), ('under_review', 'Under review'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=30)),
                ('risk_rating', models.CharField(default='medium', max_length=20)),
                ('default_currency', models.CharField(default='BIF', max_length=3)),
                ('statement_descriptor', models.CharField(blank=True, max_length=22)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeneficialOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=120)),
                ('ownership_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pep', models.BooleanField(default=False)),
                ('sanctions_match', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficial_owners', to='merchants.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_activities', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='merchants.merchant')),
            ],
            options={
                'verbose_name_plural': 'merchant activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('prefix', models.CharField(db_index=True, max_length=24)),
                ('secret_hash', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='merchants.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.merchants.models.merchant_application_reference, editable=False, max_length=30, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=160)),
                ('legal_form', models.CharField(max_length=80)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=80)),
                ('industry', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(default='BI', max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=180)),
                ('contact_role', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('expected_monthly_volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_monthly_transactions', models.PositiveIntegerField()),
                ('business_description', models.TextField()),
                ('payment_use_case', models.TextField()),
                ('settlement_alias_type', models.CharField(choices=[('MOBILE', 'Mobile number'), ('ACCOUNT', 'BurundiPay account alias')], default='MOBILE', max_length=20)),
                ('settlement_alias', models.CharField(blank=True, help_text='The BurundiPay alias proposed to receive merchant settlements.', max_length=160)),
                ('settlement_account_name', models.CharField(blank=True, help_text='Name registered on the proposed BurundiPay account.', max_length=180)),
                ('referral_source', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info', 'More information required'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=24)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('consented_at', models.DateTimeField()),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_application', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merchant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='merchants.merchantapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('tax', 'Tax/NIF'), ('license', 'Business license'), ('address', 'Proof of address'), ('bank', 'Settlement account proof'), ('id', 'Representative ID'), ('other', 'Other')], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, upload_to='merchant_kyb/%Y/%m/')),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyb_documents', to='merchants.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantKYB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info', 'More information required')], default='pending', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('review_notes', models.TextField(blank=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=200)),
                ('expected_monthly_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expected_monthly_transactions', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_rating', models.CharField(default='medium', max_length=20)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyb', to='merchants.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantSettlementAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_type', models.CharField(default='MOBILE', max_length=20)),
                ('alias_value', models.CharField(max_length=160)),
                ('account_name', models.CharField(blank=True, max_length=180)),
                ('account_type', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('provider_customer_reference', models.CharField(blank=True, max_length=120)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_verification', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_accounts', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantWebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('events', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='merchants.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='merchantapplication',
            index=models.Index(fields=['status', 'created_at'], name='merchants_m_status_27c68c_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchantsettlementaccount',
            constraint=models.UniqueConstraint(fields=('merchant', 'alias_type', 'alias_value'), name='uq_merchant_settlement_alias'),
        ),
    ]
