# Generated by Django 5.2.17 on 2026-09-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapplication',
            name='address_document',
            field=models.FileField(blank=True, upload_to='merchant_applications/%Y/%m/', verbose_name='Proof of business address'),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='bank_document',
            field=models.FileField(blank=True, upload_to='merchant_applications/%Y/%m/', verbose_name='Settlement account proof'),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='id_document',
            field=models.FileField(blank=True, upload_to='merchant_applications/%Y/%m/', verbose_name='Representative ID'),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='license_document',
            field=models.FileField(blank=True, upload_to='merchant_applications/%Y/%m/', verbose_name='Business licence (if your activity is regulated)'),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='mcc',
            field=models.CharField(blank=True, help_text='4-digit MCC if you know it; AmatoPay assigns one otherwise.', max_length=8, verbose_name='Merchant category code'),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='registration_document',
            field=models.FileField(blank=True, upload_to='merchant_applications/%Y/%m/', verbose_name='Business registration certificate'),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='source_of_funds',
            field=models.CharField(blank=True, help_text='Where the money your business collects comes from (e.g. product sales, service fees).', max_length=200),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='statement_descriptor',
            field=models.CharField(blank=True, help_text='Short name shown to payers on their statement (max 22 characters).', max_length=22),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='tax_document',
            field=models.FileField(blank=True, upload_to='merchant_applications/%Y/%m/', verbose_name='Tax / NIF certificate'),
        ),
        migrations.DeleteModel(
            name='BeneficialOwner',
        ),
    ]
