# Generated by Django 5.2.17 on 2026-08-09 10:00

import apps.merchants.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchantactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.merchants.models.merchant_application_reference, editable=False, max_length=30, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=160)),
                ('legal_form', models.CharField(max_length=80)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=80)),
                ('industry', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(default='BI', max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=180)),
                ('contact_role', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('expected_monthly_volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_monthly_transactions', models.PositiveIntegerField()),
                ('business_description', models.TextField()),
                ('payment_use_case', models.TextField()),
                ('referral_source', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_info', 'More information required'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=24)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('consented_at', models.DateTimeField()),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merchant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='merchants.merchantapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='merchantapplication',
            index=models.Index(fields=['status', 'created_at'], name='merchants_m_status_27c68c_idx'),
        ),
    ]
