# Generated by Django 5.2.17 on 2026-09-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchantapplication_address_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='instant_settlement_enabled',
            field=models.BooleanField(default=False, help_text='AmatoPay-granted capability. When enabled, this merchant may create checkout sessions with require_delivery_confirmation=false — funds auto-release to the merchant as soon as the payment is collected, with no secure-code delivery gate. Grant only after a risk review.'),
        ),
    ]
