# Generated by Django 5.2.17 on 2026-08-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchantapplication_merchantapplicationreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapplication',
            name='settlement_account_name',
            field=models.CharField(blank=True, help_text='Name registered on the proposed BurundiPay account.', max_length=180),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='settlement_alias',
            field=models.CharField(blank=True, help_text='The BurundiPay alias proposed to receive merchant settlements.', max_length=160),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='settlement_alias_type',
            field=models.CharField(choices=[('MOBILE', 'Mobile number'), ('ACCOUNT', 'BurundiPay account alias')], default='MOBILE', max_length=20),
        ),
    ]
