# Generated by Django 5.2.17 on 2026-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_instant_settlement_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='qr_payments_enabled',
            field=models.BooleanField(default=False, help_text="AmatoPay-granted capability. When enabled, this merchant may create checkout sessions with payment_method=QR — the payer scans AmatoPay's shared QR code and pays through their own banking app instead of approving a request pushed to a typed alias."),
        ),
    ]
