# Generated by Django 5.2.17 on 2026-08-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchantapplication_settlement_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantapikey',
            name='mode',
        ),
    ]
