# Generated by Django 5.2.17 on 2026-08-11 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_members_to_direct_owners(apps, schema_editor):
    Merchant = apps.get_model("merchants", "Merchant")
    MerchantMember = apps.get_model("merchants", "MerchantMember")
    assigned_users = set()
    for merchant in Merchant.objects.filter(owner__isnull=True).iterator():
        membership = (
            MerchantMember.objects.filter(merchant=merchant, active=True)
            .order_by(models.Case(models.When(role="owner", then=0), default=1), "created_at")
            .first()
        )
        if membership and membership.user_id not in assigned_users:
            merchant.owner_id = membership.user_id
            merchant.save(update_fields=["owner"])
            assigned_users.add(membership.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_remove_merchantapikey_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            move_members_to_direct_owners, migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name='MerchantMember',
        ),
    ]
