# Generated by Django 5.2.17 on 2026-08-12 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_secret', models.CharField(editable=False, max_length=120, unique=True)),
                ('order_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('fee_source', models.CharField(blank=True, max_length=30)),
                ('fee_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('payer_alias', models.CharField(blank=True, max_length=160)),
                ('payer_display_name', models.CharField(blank=True, max_length=180)),
                ('return_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('awaiting_alias', 'Awaiting alias'), ('alias_verified', 'Alias verified'), ('awaiting_payment', 'Awaiting payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_sessions', to='merchants.merchant')),
                ('plan_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='billing.merchantplanassignment')),
                ('pricing_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='billing.pricingplan')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_session_amount_positive'), models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0), ('fee_amount__lt', models.F('amount'))), name='ck_session_fee_valid')],
            },
        ),
    ]
