# Generated by Django 5.2.17 on 2026-09-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='require_delivery_confirmation',
            field=models.BooleanField(default=True, help_text='When false, the payment settles to the merchant immediately on collection with no delivery-confirmation hold. Only permitted for merchants with instant_settlement_enabled.'),
        ),
    ]
