# Generated by Django 5.2.17 on 2026-08-09 08:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def preserve_session_fees(apps, schema_editor):
    PaymentSession = apps.get_model("checkout", "PaymentSession")
    for session in PaymentSession.objects.all().iterator():
        rate = Decimal("0.0000")
        if session.amount:
            rate = (session.fee_amount * Decimal("100") / session.amount).quantize(
                Decimal("0.0001")
            )
        session.fee_percentage = rate
        session.fee_source = "LEGACY"
        session.verification_status_at_transaction = "PARTIAL"
        session.fee_calculated_at = session.created_at
        session.save(
            update_fields=[
                "fee_percentage",
                "fee_source",
                "verification_status_at_transaction",
                "fee_calculated_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_merchantfeeoverride_verificationfeerule_and_more"),
        ("checkout", "0002_payment_session_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsession",
            name="fee_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="fee_percentage",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="fee_source",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="merchant_fee_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkout_sessions",
                to="billing.merchantfeeoverride",
            ),
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="verification_fee_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkout_sessions",
                to="billing.verificationfeerule",
            ),
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="verification_status_at_transaction",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(preserve_session_fees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="paymentsession",
            name="fee_bearer",
        ),
        migrations.RemoveField(
            model_name="paymentsession",
            name="pricing_plan_name",
        ),
        migrations.RemoveField(
            model_name="paymentsession",
            name="tax_amount",
        ),
    ]
