# Generated by Django 5.2.17 on 2026-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_paymentsession_require_delivery_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='payment_method',
            field=models.CharField(choices=[('ALIAS', 'Push to alias'), ('QR', 'Scan QR code')], default='ALIAS', max_length=10),
        ),
    ]
