# Generated by Django 5.2.17 on 2026-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_merchantfeeoverride_verificationfeerule_and_more'),
        ('checkout', '0003_remove_paymentsession_fee_bearer_and_more'),
        ('merchants', '0002_merchantactivity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentsession',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_session_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentsession',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0), ('fee_amount__lt', models.F('amount'))), name='ck_session_fee_valid'),
        ),
    ]
