# Generated by Django 5.2.17 on 2026-08-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_paymentsession_ck_session_amount_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='payer_alias',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
