# Generated by Django 5.2.17 on 2026-08-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_paymentsession_payer_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsession',
            name='mode',
        ),
    ]
