# Generated by Django 5.2.17 on 2026-08-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_pricingplan_merchantplanassignment'),
        ('checkout', '0006_remove_paymentsession_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='plan_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='billing.merchantplanassignment'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='billing.pricingplan'),
        ),
    ]
