# Generated by Django 5.2.17 on 2026-08-11 09:51

from django.db import migrations


def preserve_legacy_override_source(apps, schema_editor):
    PaymentSession = apps.get_model("checkout", "PaymentSession")
    PaymentSession.objects.filter(fee_source="MERCHANT_OVERRIDE").update(
        fee_source="LEGACY"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_paymentsession_plan_assignment_and_more'),
    ]

    operations = [
        migrations.RunPython(
            preserve_legacy_override_source, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='merchant_fee_override',
        ),
    ]
