# Generated by Django 5.2.17 on 2026-08-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_paymentsession_merchant_fee_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsession',
            name='verification_fee_rule',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='verification_status_at_transaction',
        ),
    ]
