"""Render a :class:`~apps.compliance.reports.ReportData` to CSV or PDF bytes."""

from __future__ import annotations

import csv
import io

from django.conf import settings
from django.utils import timezone


def _meta_lines(meta: dict) -> list[tuple[str, str]]:
    return [
        ("Report", meta.get("title", "")),
        ("Type", meta.get("type_label", "")),
        ("Period", f"{meta.get('period_start')} to {meta.get('period_end')}"),
        ("Generated", meta.get("generated_at") or timezone.now().strftime("%Y-%m-%d %H:%M")),
        ("Generated by", meta.get("generated_by") or "—"),
        ("Rows", str(len(meta.get("rows", [])))),
    ]


def to_csv(report, meta: dict) -> bytes:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow([f"{settings.COMPANY_NAME} — compliance report"])
    for label, value in _meta_lines({**meta, "rows": report.rows}):
        writer.writerow([label, value])
    for label, value in (report.summary or {}).items():
        writer.writerow([f"summary:{label}", value])
    writer.writerow([])
    writer.writerow(report.columns)
    writer.writerows(report.rows)
    return buffer.getvalue().encode("utf-8-sig")


def to_pdf(report, meta: dict) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        LongTable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        TableStyle,
    )

    styles = getSampleStyleSheet()
    small = styles["BodyText"].clone("small", fontSize=7, leading=9)
    header = styles["BodyText"].clone(
        "th", fontSize=7, leading=9, textColor=colors.white
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=14 * mm,
        rightMargin=14 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title=meta.get("title", "Compliance report"),
    )

    story = [
        Paragraph(f"<b>{settings.COMPANY_NAME}</b> — {meta.get('title', 'Compliance report')}", styles["Title"]),
    ]
    for label, value in _meta_lines({**meta, "rows": report.rows}):
        story.append(Paragraph(f"<b>{label}:</b> {value}", styles["Normal"]))
    if report.summary:
        summary = "  ·  ".join(f"{k}: {v}" for k, v in report.summary.items())
        story.append(Spacer(1, 4))
        story.append(Paragraph(f"<b>Summary</b> — {summary}", styles["Normal"]))
    story.append(Spacer(1, 10))

    head = [Paragraph(str(c), header) for c in report.columns]
    body = [
        [Paragraph(("" if cell is None else str(cell)), small) for cell in row]
        for row in report.rows
    ] or [[Paragraph("No records in this period.", small)] + [""] * (len(report.columns) - 1)]

    table = LongTable([head] + body, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#071f2b")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d3dedb")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f9f8")]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    story.append(table)
    doc.build(story)
    return buffer.getvalue()


def as_response(report, meta: dict, fmt: str):
    from django.http import HttpResponse

    slug = (meta.get("slug") or "report").replace(" ", "-")
    if fmt == "pdf":
        content, ctype, ext = to_pdf(report, meta), "application/pdf", "pdf"
    else:
        content, ctype, ext = to_csv(report, meta), "text/csv", "csv"
    response = HttpResponse(content, content_type=ctype)
    response["Content-Disposition"] = f'attachment; filename="{slug}.{ext}"'
    return response
