# Generated by Django 5.2.15 on 2026-07-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='sec_request_ip_addr_b43fe4_idx',
            old_name='sec_req_ip_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='sec_request_status__95eb8b_idx',
            old_name='sec_req_sc_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='sec_alert_resolve_c2bfbf_idx',
            old_name='sec_alert_res_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='sec_alert_ip_addr_fa6762_idx',
            old_name='sec_alert_ip_ts_idx',
        ),
    ]
