# Generated by Django 5.2.15 on 2026-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_rename_sec_req_ip_ts_idx_sec_request_ip_addr_b43fe4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='alert_type',
            field=models.CharField(choices=[('brute_force', 'Brute Force'), ('rate_limit', 'Rate Limit'), ('scanning', 'Scanning'), ('injection', 'Injection Attempt'), ('param_pollution', 'Parameter Pollution'), ('header_injection', 'Header Injection'), ('large_payload', 'Large Payload'), ('suspicious_method', 'Suspicious Method'), ('path_traversal', 'Path Traversal'), ('suspicious_ua', 'Suspicious User-Agent'), ('blocked_attempt', 'Blocked IP Attempt'), ('admin_probe', 'Admin Probe')], db_index=True, max_length=30),
        ),
    ]
