# Generated by Django 5.2.17 on 2026-08-12 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('effective_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=255)),
                ('contracted_transactions_per_month', models.PositiveIntegerField(blank=True, help_text='Contract-specific monthly allowance. Leave blank to use the plan allowance.', null=True)),
                ('contracted_monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Signed monthly price. Leave blank to use the plan price.', max_digits=20, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_merchant_plans', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_assignments', to='merchants.merchant')),
            ],
            options={
                'ordering': ['merchant', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='A list of plan features.')),
                ('included_transactions_per_month', models.PositiveIntegerField(blank=True, help_text='Included successful payments per calendar month; blank means unlimited.', null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Published monthly plan price; blank means contract pricing.', max_digits=20, null=True)),
                ('transaction_fee_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage fee per transaction for pay-as-you-go plans.', max_digits=7, null=True)),
                ('extension_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for a transaction extension pack.', max_digits=20, null=True)),
                ('extension_transactions', models.PositiveIntegerField(blank=True, help_text='Number of extra transactions in an extension pack.', null=True)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_price__isnull', True), ('monthly_price__gte', 0), _connector='OR'), name='ck_plan_monthly_price_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('payer_alias', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('active', 'Active — plan assigned'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_plan_requests', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_requests', to='merchants.merchant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_requests', to='billing.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanExtensionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('extra_transactions', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extension_orders', to='billing.merchantplanassignment')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_extension_orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extension_orders', to='billing.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='merchantplanassignment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_assignments', to='billing.pricingplan'),
        ),
        migrations.AddIndex(
            model_name='merchantplanassignment',
            index=models.Index(fields=['merchant', 'active', 'effective_from'], name='billing_mer_merchan_79ff44_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchantplanassignment',
            constraint=models.UniqueConstraint(fields=('merchant', 'effective_from'), name='uq_merchant_plan_effective'),
        ),
        migrations.AddConstraint(
            model_name='merchantplanassignment',
            constraint=models.CheckConstraint(condition=models.Q(('contracted_monthly_price__isnull', True), ('contracted_monthly_price__gte', 0), _connector='OR'), name='ck_contract_monthly_price_nonnegative'),
        ),
    ]
