# Generated by Django 5.2.17 on 2026-08-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('cecf', '0002_remove_rtprequest_extension_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='extension_price',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='extension_transactions',
        ),
        migrations.DeleteModel(
            name='PlanExtensionOrder',
        ),
    ]
