# Generated by Django 5.2.17 on 2026-08-09 08:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def seed_verification_fee_rules(apps, schema_editor):
    VerificationFeeRule = apps.get_model("billing", "VerificationFeeRule")
    effective_from = timezone.now()
    VerificationFeeRule.objects.bulk_create(
        [
            VerificationFeeRule(
                code="PARTIAL",
                name="Partial KYC/KYB",
                fee_percentage=Decimal("3.0000"),
                active=True,
                effective_from=effective_from,
                change_reason="Initial KYC/KYB fee configuration",
            ),
            VerificationFeeRule(
                code="VERIFIED",
                name="Fully Verified KYC/KYB",
                fee_percentage=Decimal("2.0000"),
                active=True,
                effective_from=effective_from,
                change_reason="Initial KYC/KYB fee configuration",
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_pricing_configuration"),
        ("merchants", "0002_merchantactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantFeeOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fee_percentage", models.DecimalField(decimal_places=4, max_digits=7)),
                ("reason", models.CharField(max_length=255)),
                ("effective_from", models.DateTimeField(db_index=True)),
                (
                    "effective_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_fee_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_fee_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_overrides",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["merchant", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="VerificationFeeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PARTIAL", "Partial KYC/KYB"),
                            ("VERIFIED", "Fully verified KYC/KYB"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fee_percentage", models.DecimalField(decimal_places=4, max_digits=7)),
                ("active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField(db_index=True)),
                (
                    "effective_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("change_reason", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["code", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["code", "active", "effective_from"],
                        name="billing_ver_code_5ae47e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "effective_from"),
                        name="uq_fee_rule_code_effective",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fee_percentage__gte", 0), ("fee_percentage__lte", 100)
                        ),
                        name="ck_fee_rule_percentage",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_verification_fee_rules, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="MerchantPricing",
        ),
        migrations.DeleteModel(
            name="PricingPlan",
        ),
        migrations.AddIndex(
            model_name="merchantfeeoverride",
            index=models.Index(
                fields=["merchant", "active", "effective_from"],
                name="billing_mer_merchan_6c7c07_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantfeeoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fee_percentage__gte", 0), ("fee_percentage__lte", 100)
                ),
                name="ck_merchant_override_percentage",
            ),
        ),
    ]
