# Generated by Django 5.2.17 on 2026-08-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_merchantfeeoverride_verificationfeerule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentLink',
        ),
    ]
