# Generated by Django 5.2.17 on 2026-08-11 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_delete_paymentlink'),
        ('merchants', '0005_remove_merchantapikey_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('partial_fee_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('verified_fee_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('partial_fee_percentage__gte', 0), ('partial_fee_percentage__lte', 100)), name='ck_plan_partial_percentage'), models.CheckConstraint(condition=models.Q(('verified_fee_percentage__gte', 0), ('verified_fee_percentage__lte', 100)), name='ck_plan_verified_percentage'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('currency',), name='uq_default_plan_per_currency')],
            },
        ),
        migrations.CreateModel(
            name='MerchantPlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('effective_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=255)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_merchant_plans', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_assignments', to='merchants.merchant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_assignments', to='billing.pricingplan')),
            ],
            options={
                'ordering': ['merchant', '-effective_from'],
                'indexes': [models.Index(fields=['merchant', 'active', 'effective_from'], name='billing_mer_merchan_79ff44_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'effective_from'), name='uq_merchant_plan_effective')],
            },
        ),
    ]
