# Generated by Django 5.2.17 on 2026-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_pricingplan_merchantplanassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantplanassignment',
            name='contracted_transactions_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Contract-specific monthly allowance. Leave blank to use the plan allowance.', null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='included_transactions_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Included successful payments per calendar month; blank means unlimited.', null=True),
        ),
    ]
