# Generated by Django 5.2.17 on 2026-08-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_merchantplanassignment_contracted_transactions_per_month_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricingplan',
            name='ck_plan_partial_percentage',
        ),
        migrations.RemoveConstraint(
            model_name='pricingplan',
            name='ck_plan_verified_percentage',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='partial_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='verified_fee_percentage',
        ),
    ]
