# Generated by Django 5.2.17 on 2026-08-11 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_pricingplan_ck_plan_partial_percentage_and_more'),
        ('merchants', '0005_remove_merchantapikey_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricingplan',
            name='uq_default_plan_per_currency',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='is_default',
        ),
        migrations.AddField(
            model_name='merchantplanassignment',
            name='contracted_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Signed monthly price. Leave blank to use the plan price.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Published monthly plan price; blank means contract pricing.', max_digits=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='merchantplanassignment',
            constraint=models.CheckConstraint(condition=models.Q(('contracted_monthly_price__isnull', True), ('contracted_monthly_price__gte', 0), _connector='OR'), name='ck_contract_monthly_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_price__isnull', True), ('monthly_price__gte', 0), _connector='OR'), name='ck_plan_monthly_price_nonnegative'),
        ),
    ]
