# Generated by Django 5.2.17 on 2026-08-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_pricingplan_uq_default_plan_per_currency_and_more'),
        ('checkout', '0008_remove_paymentsession_merchant_fee_override'),
        ('payments', '0009_remove_payment_merchant_fee_override_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantFeeOverride',
        ),
    ]
