# Generated by Django 5.2.17 on 2026-08-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_delete_merchantfeeoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='A list of plan features.'),
        ),
    ]
