# Generated by Django 5.2.17 on 2026-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_pricingplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='extension_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for a transaction extension pack.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='extension_transactions',
            field=models.PositiveIntegerField(blank=True, help_text='Number of extra transactions in an extension pack.', null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='transaction_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Percentage fee per transaction for pay-as-you-go plans.', max_digits=7, null=True),
        ),
    ]
