
# Generated by Django 5.2.17 on 2026-08-12 09:41

from django.db import migrations

PLANS_DATA = [
    {
        "code": "starter",
        "name": "Starter",
        "monthly_price": 250000,
        "included_transactions_per_month": 160,
        "extension_transactions": 80,
        "extension_price": 150000,
        "features": [
            "Hosted checkout",
            "Signed webhooks",
            "Payment links",
            "API access",
        ],
    },
    {
        "code": "standard",
        "name": "Standard",
        "monthly_price": 500000,
        "included_transactions_per_month": 320,
        "extension_transactions": 160,
        "extension_price": 300000,
        "features": [
            "Hosted checkout",
            "Signed webhooks",
            "Payment links",
            "API access",
            "Delivery protection",
            "Request logs",
        ],
    },
    {
        "code": "business",
        "name": "Business",
        "monthly_price": 850000,
        "included_transactions_per_month": 544,
        "extension_transactions": 272,
        "extension_price": 510000,
        "features": [
            "Hosted checkout",
            "Signed webhooks",
            "Payment links",
            "API access",
            "Delivery protection",
            "Request logs",
            "Refunds",
            "Team workspaces",
        ],
    },
    {
        "code": "business-plus",
        "name": "Business Plus",
        "monthly_price": 1050000,
        "included_transactions_per_month": 672,
        "extension_transactions": 336,
        "extension_price": 630000,
        "features": [
            "Hosted checkout",
            "Signed webhooks",
            "Payment links",
            "API access",
            "Delivery protection",
            "Request logs",
            "Refunds",
            "Team workspaces",
            "Priority support",
            "KYB fast-track",
        ],
    },
    {
        "code": "premium",
        "name": "Premium",
        "monthly_price": 1500000,
        "included_transactions_per_month": 960,
        "extension_transactions": 480,
        "extension_price": 900000,
        "features": [
            "Hosted checkout",
            "Signed webhooks",
            "Payment links",
            "API access",
            "Delivery protection",
            "Request logs",
            "Refunds",
            "Team workspaces",
            "Priority support",
            "KYB fast-track",
            "Dedicated account manager",
            "Custom settlement schedule",
        ],
    },
    {
        "code": "enterprise",
        "name": "Enterprise",
        "monthly_price": 2000000,
        "included_transactions_per_month": 1280,
        "extension_transactions": 640,
        "extension_price": 1200000,
        "features": [
            "Hosted checkout",
            "Signed webhooks",
            "Payment links",
            "API access",
            "Delivery protection",
            "Request logs",
            "Refunds",
            "Team workspaces",
            "Priority support",
            "KYB fast-track",
            "Dedicated account manager",
            "Custom settlement schedule",
            "SLA guarantee",
            "Compliance reporting",
        ],
    },
    {
        "code": "unlimited",
        "name": "Unlimited",
        "monthly_price": 5000000,
        "included_transactions_per_month": None,
        "features": [
            "Unlimited transactions",
            "All Enterprise features",
            "White-glove onboarding",
            "Custom integration support",
            "SLA guarantee",
            "Compliance reporting",
        ],
    },
    {
        "code": "pay-as-you-go",
        "name": "Pay-as-you-go",
        "monthly_price": 0,
        "included_transactions_per_month": 0,
        "transaction_fee_percentage": 0.05,
        "description": "5% fee on each transaction. No monthly commitment.",
        "features": [
            "Hosted checkout",
            "Signed webhooks",
            "API access",
            "No monthly fee",
        ],
    },
]

def seed_plans(apps, schema_editor):
    PricingPlan = apps.get_model('billing', 'PricingPlan')
    for plan_data in PLANS_DATA:
        PricingPlan.objects.update_or_create(code=plan_data["code"], defaults=plan_data)

def unseed_plans(apps, schema_editor):
    PricingPlan = apps.get_model('billing', 'PricingPlan')
    for plan_data in PLANS_DATA:
        PricingPlan.objects.filter(code=plan_data["code"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_pricingplan_extension_price_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_plans, unseed_plans),
    ]
