# Generated by Django 5.2.17 on 2026-08-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_seed_plan_features'),
        ('checkout', '0009_remove_verification_fee_rule'),
        ('payments', '0010_remove_verification_fee_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationFeeRule',
        ),
    ]
