# Generated by Django 5.2.17 on 2026-08-12 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_remove_verification_fee_rule'),
        ('merchants', '0006_merchant_owner_merchantapplication_applicant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('payer_alias', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('active', 'Active — plan assigned'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_plan_requests', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_requests', to='merchants.merchant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_requests', to='billing.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
