# Generated by Django 5.2.17 on 2026-08-08 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0001_initial"),
        ("payments", "0001_initial"),
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AliasVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_id", models.CharField(max_length=100, unique=True)),
                ("alias_type", models.CharField(max_length=20)),
                ("alias_value", models.CharField(max_length=160)),
                ("found", models.BooleanField(default=False)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("display_name", models.CharField(blank=True, max_length=180)),
                ("provider_customer_ref", models.CharField(blank=True, max_length=120)),
                ("account_type", models.CharField(blank=True, max_length=30)),
                ("currency", models.CharField(default="BIF", max_length=3)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alias_verifications",
                        to="checkout.paymentsession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="P2PRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_id", models.CharField(max_length=100, unique=True)),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("status", models.CharField(default="processing", max_length=30)),
                ("last_callback_at", models.DateTimeField(blank=True, null=True)),
                ("raw_request", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "settlement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="p2p",
                        to="settlements.settlement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="P2PCallback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=120, unique=True)),
                ("status", models.CharField(max_length=30)),
                ("reason_code", models.CharField(blank=True, max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "p2p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="callbacks",
                        to="cecf.p2prequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RTPRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_id", models.CharField(max_length=100, unique=True)),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("status", models.CharField(default="pending", max_length=30)),
                ("last_callback_at", models.DateTimeField(blank=True, null=True)),
                ("raw_request", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rtp",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RTPCallback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=120, unique=True)),
                ("status", models.CharField(max_length=30)),
                ("reason_code", models.CharField(blank=True, max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "rtp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="callbacks",
                        to="cecf.rtprequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
