# Generated by Django 5.2.17 on 2026-08-12 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('checkout', '0001_initial'),
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('alias_type', models.CharField(max_length=20)),
                ('alias_value', models.CharField(max_length=160)),
                ('found', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=180)),
                ('provider_customer_ref', models.CharField(blank=True, max_length=120)),
                ('account_type', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_alias_verifications', to='merchants.merchant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alias_verifications', to='checkout.paymentsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Primary CECF gateway', max_length=100)),
                ('base_url', models.URLField(help_text='CECF/MobileCash API base URL')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('creditor_alias', models.CharField(blank=True, max_length=80)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=15)),
                ('verify_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uq_active_cecf_gateway')],
            },
        ),
        migrations.CreateModel(
            name='GatewayTransactionPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rail', models.CharField(choices=[('RTP', 'RTP collection'), ('P2P', 'P2P payout')], db_index=True, max_length=3)),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('trx_ref', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('succeeded', models.BooleanField(db_index=True, default=False)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rail', 'trx_ref', '-created_at'], name='idx_gateway_poll_trx')],
            },
        ),
        migrations.CreateModel(
            name='P2PRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='Gateway trxRef used by TRANSACTION_BY_REFERENCE monitoring.', max_length=120)),
                ('status', models.CharField(default='processing', max_length=30)),
                ('last_callback_at', models.DateTimeField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('next_poll_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('poll_attempts', models.PositiveIntegerField(default=0)),
                ('consecutive_poll_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_poll_error', models.TextField(blank=True)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='p2p', to='settlements.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='P2PCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('p2p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callbacks', to='cecf.p2prequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RTPRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='Gateway trxRef used by TRANSACTION_BY_REFERENCE monitoring.', max_length=120)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('last_callback_at', models.DateTimeField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('release_code_ciphertext', models.TextField(blank=True, editable=False)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('next_poll_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('poll_attempts', models.PositiveIntegerField(default=0)),
                ('consecutive_poll_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_poll_error', models.TextField(blank=True)),
                ('extension_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='billing.planextensionorder')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='payments.payment')),
                ('plan_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='billing.planrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RTPCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rtp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callbacks', to='cecf.rtprequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='p2prequest',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider_reference',), name='uq_p2p_gateway_trx_ref'),
        ),
        migrations.AddConstraint(
            model_name='rtprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider_reference',), name='uq_rtp_gateway_trx_ref'),
        ),
    ]
