# Generated by Django 5.2.17 on 2026-08-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cecf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtprequest',
            name='extension_order',
        ),
    ]
