# Generated by Django 5.2.17 on 2026-08-08 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Primary CECF gateway", max_length=100),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("mobilecash", "BurundiPay / MobileCash"),
                            ("legacy", "Legacy AmatoPay facade"),
                        ],
                        default="mobilecash",
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(help_text="CECF/MobileCash API base URL")),
                ("username", models.CharField(blank=True, max_length=150)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("creditor_alias", models.CharField(blank=True, max_length=80)),
                ("client_id", models.CharField(blank=True, max_length=120)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=15)),
                ("verify_tls", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-is_active", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_active_cecf_gateway",
                    )
                ],
            },
        ),
    ]
