# Generated by Django 5.2.17 on 2026-08-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecf', '0003_simplify_mobilecash_config'),
        ('merchants', '0004_merchantapplication_settlement_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliasverification',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_alias_verifications', to='merchants.merchant'),
        ),
    ]
