# Generated by Django 5.2.17 on 2026-09-05 22:49

import django.db.models.deletion
from django.db import migrations, models


def rtp_to_collection(apps, schema_editor):
    for model_name in ("GatewayRequest", "GatewayTransactionPoll"):
        model = apps.get_model("cecf", model_name)
        model.objects.filter(rail="RTP").update(rail="COLLECTION")


def collection_to_rtp(apps, schema_editor):
    for model_name in ("GatewayRequest", "GatewayTransactionPoll"):
        model = apps.get_model("cecf", model_name)
        model.objects.filter(rail="COLLECTION").update(rail="RTP")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_pricingplan_extension_price_and_more'),
        ('cecf', '0003_merge_gateway_request'),
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayrequest',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='gatewayrequest',
            name='plan_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection', to='billing.planrequest'),
        ),
        migrations.AlterField(
            model_name='gatewayrequest',
            name='rail',
            field=models.CharField(choices=[('COLLECTION', 'Collection'), ('P2P', 'P2P payout')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='gatewayrequest',
            name='release_code_ciphertext',
            field=models.TextField(blank=True, editable=False, help_text='Collection rail only.'),
        ),
        migrations.AlterField(
            model_name='gatewaytransactionpoll',
            name='rail',
            field=models.CharField(choices=[('COLLECTION', 'Collection'), ('P2P', 'P2P payout')], db_index=True, max_length=12),
        ),
        migrations.RunPython(rtp_to_collection, collection_to_rtp),
    ]
