# Generated by Django 5.2.17 on 2026-09-11 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecf', '0004_alter_gatewayrequest_payment_and_more'),
        ('payments', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='qr_code_text',
            field=models.TextField(blank=True, help_text="AmatoPay's own bank-registered static IPS QR payload (for the creditor_alias above). Rendered as a scannable image on QR checkout pages. Not required unless QR payments are used."),
        ),
        migrations.CreateModel(
            name='QRPaymentWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_header_uuid', models.CharField(blank=True, db_index=True, max_length=120)),
                ('qr_extension_uuid', models.CharField(blank=True, db_index=True, max_length=120)),
                ('raw_scan_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('matched', 'Matched'), ('expired', 'Expired'), ('failed', 'Failed')], default='watching', max_length=12)),
                ('matched_trx_ref', models.CharField(blank=True, max_length=120)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('next_poll_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('poll_attempts', models.PositiveIntegerField(default=0)),
                ('consecutive_poll_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_poll_error', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qr_watch', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
