# Generated by Django 5.2.17 on 2026-08-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecf', '0004_aliasverification_merchant'),
        ('payments', '0007_delete_paymentreceipt'),
        ('settlements', '0004_settlement_ck_settlement_amounts_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2prequest',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Gateway trxRef used by TRANSACTION_BY_REFERENCE monitoring.', max_length=120),
        ),
        migrations.AlterField(
            model_name='rtprequest',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Gateway trxRef used by TRANSACTION_BY_REFERENCE monitoring.', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='p2prequest',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider_reference',), name='uq_p2p_gateway_trx_ref'),
        ),
        migrations.AddConstraint(
            model_name='rtprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider_reference',), name='uq_rtp_gateway_trx_ref'),
        ),
    ]
