# Generated by Django 5.2.17 on 2026-08-09 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecf', '0005_alter_p2prequest_provider_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2prequest',
            name='consecutive_poll_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='last_poll_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='next_poll_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2prequest',
            name='poll_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rtprequest',
            name='consecutive_poll_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rtprequest',
            name='last_poll_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rtprequest',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtprequest',
            name='next_poll_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rtprequest',
            name='poll_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GatewayTransactionPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rail', models.CharField(choices=[('RTP', 'RTP collection'), ('P2P', 'P2P payout')], db_index=True, max_length=3)),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('trx_ref', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('succeeded', models.BooleanField(db_index=True, default=False)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rail', 'trx_ref', '-created_at'], name='idx_gateway_poll_trx')],
            },
        ),
    ]
