# Generated by Django 5.2.17 on 2026-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecf', '0005_gatewayconfig_qr_code_text_qrpaymentwatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrpaymentwatch',
            name='qr_extension_uuid',
        ),
        migrations.AddField(
            model_name='qrpaymentwatch',
            name='qr_extension_uuids',
            field=models.JSONField(blank=True, default=list, help_text='Every qrExtensionUUID from the scan response (top-level + extensions[]).'),
        ),
        migrations.AddField(
            model_name='qrpaymentwatch',
            name='qr_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
