# Generated by Django 5.2.17 on 2026-09-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cecf', '0006_remove_qrpaymentwatch_qr_extension_uuid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GatewayTransactionPoll',
        ),
    ]
