# Generated by Django 5.2.17 on 2026-08-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_extension_order'),
        ('cecf', '0007_rtprequest_release_code_ciphertext'),
        ('payments', '0009_remove_payment_merchant_fee_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtprequest',
            name='extension_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='billing.planextensionorder'),
        ),
        migrations.AlterField(
            model_name='rtprequest',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='payments.payment'),
        ),
    ]
