# Generated by Django 5.2.17 on 2026-08-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_planrequest'),
        ('cecf', '0008_rtp_extension_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtprequest',
            name='plan_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='billing.planrequest'),
        ),
    ]
