# Generated by Django 5.2.17 on 2026-08-08 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor", models.CharField(blank=True, max_length=160)),
                ("action", models.CharField(max_length=100)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("previous_hash", models.CharField(blank=True, max_length=64)),
                (
                    "event_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
