# Generated by Django 5.2.17 on 2026-08-12 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=100)),
                ('retain_until', models.DateField()),
                ('legal_basis', models.CharField(default='BRB Circular 008/SP/2026', max_length=160)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(max_length=80)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuspiciousTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='open', max_length=30)),
                ('reported_to_brb', models.BooleanField(default=False)),
                ('reported_to_cnrf', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspicious_reports', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
