# Generated by Django 5.2.17 on 2026-09-05 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulatoryreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_regulatory_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='row_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='payload',
            field=models.JSONField(default=dict, editable=False, help_text='Frozen snapshot: {columns, rows, summary, generated_at}.'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='report_type',
            field=models.CharField(help_text='One of the report generators registered in compliance.reports.', max_length=80),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('reviewed', 'Reviewed'), ('submitted', 'Submitted'), ('archived', 'Archived')], default='generated', max_length=30),
        ),
    ]
