# Generated by Django 5.2.17 on 2026-08-08 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0001_initial"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=160, unique=True)),
                ("scope", models.CharField(max_length=80)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("payer_alias_type", models.CharField(blank=True, max_length=20)),
                ("payer_alias", models.CharField(blank=True, max_length=160)),
                ("payer_display_name", models.CharField(blank=True, max_length=180)),
                ("payer_reference", models.CharField(blank=True, max_length=120)),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("currency", models.CharField(default="BIF", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("alias_verified", "Alias verified"),
                            ("rtp_pending", "RTP pending"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("funds_held", "Funds held"),
                            ("delivery_pending", "Delivery pending"),
                            ("disputed", "Disputed"),
                            ("release_pending", "Release pending"),
                            ("settlement_processing", "Settlement processing"),
                            ("settled", "Settled"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                            ("fraud_blocked", "Fraud blocked"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="checkout.paymentsession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(default="amatopay", max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
