# Generated by Django 5.2.17 on 2026-08-12 18:48

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('checkout', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=160, unique=True)),
                ('scope', models.CharField(max_length=80)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('payer_alias_type', models.CharField(blank=True, max_length=20)),
                ('payer_alias', models.CharField(blank=True, max_length=160)),
                ('payer_display_name', models.CharField(blank=True, max_length=180)),
                ('payer_reference', models.CharField(blank=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('fee_source', models.CharField(blank=True, max_length=30)),
                ('fee_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('alias_verified', 'Alias verified'), ('rtp_pending', 'RTP pending'), ('awaiting_approval', 'Awaiting approval'), ('processing', 'Processing'), ('paid', 'Paid'), ('funds_held', 'Funds held'), ('delivery_pending', 'Delivery pending'), ('disputed', 'Disputed'), ('release_pending', 'Release pending'), ('settlement_processing', 'Settlement processing'), ('settled', 'Settled'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('expired', 'Expired'), ('fraud_blocked', 'Fraud blocked')], default='created', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('release_code_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('release_code_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('release_code_locked_at', models.DateTimeField(blank=True, null=True)),
                ('release_code_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='merchants.merchant')),
                ('plan_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.merchantplanassignment')),
                ('pricing_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.pricingplan')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='checkout.paymentsession')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='amatopay', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_source', models.CharField(choices=[('PRICING_PLAN', 'Pricing plan'), ('PAY_AS_YOU_GO', 'Pay-as-you-go'), ('LEGACY', 'Migrated legacy fee')], max_length=30)),
                ('calculated_at', models.DateTimeField()),
                ('plan_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_fees', to='billing.merchantplanassignment')),
                ('pricing_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_fees', to='billing.pricingplan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_fee', to='payments.payment')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0), ('fee_amount__lt', models.F('amount'))), name='ck_payment_fee_valid'),
        ),
        migrations.AddIndex(
            model_name='transactionfee',
            index=models.Index(fields=['fee_source', 'calculated_at'], name='payments_tr_fee_sou_42a559_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionfee',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0), ('fee_amount__gte', 0), ('net_amount__gt', 0)), name='ck_transaction_fee_amounts'),
        ),
        migrations.AddConstraint(
            model_name='transactionfee',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(models.F('fee_amount'), '+', models.F('net_amount')))), name='ck_transaction_fee_balanced'),
        ),
    ]
