# Generated by Django 5.2.17 on 2026-09-05 22:49

from django.db import migrations, models


def rtp_to_collection(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.filter(status="rtp_pending").update(status="collection_pending")


def collection_to_rtp(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.filter(status="collection_pending").update(status="rtp_pending")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('alias_verified', 'Alias verified'), ('collection_pending', 'Collection pending'), ('awaiting_approval', 'Awaiting approval'), ('processing', 'Processing'), ('paid', 'Paid'), ('funds_held', 'Funds held'), ('delivery_pending', 'Delivery pending'), ('disputed', 'Disputed'), ('release_pending', 'Release pending'), ('settlement_processing', 'Settlement processing'), ('settled', 'Settled'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('expired', 'Expired'), ('fraud_blocked', 'Fraud blocked')], default='created', max_length=30),
        ),
        migrations.RunPython(rtp_to_collection, collection_to_rtp),
    ]
