# Generated by Django 5.2.17 on 2026-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('alias_verified', 'Alias verified'), ('qr_pending', 'Awaiting QR scan'), ('collection_pending', 'Collection pending'), ('awaiting_approval', 'Awaiting approval'), ('processing', 'Processing'), ('paid', 'Paid'), ('funds_held', 'Funds held'), ('delivery_pending', 'Delivery pending'), ('disputed', 'Disputed'), ('release_pending', 'Release pending'), ('settlement_processing', 'Settlement processing'), ('settled', 'Settled'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('expired', 'Expired'), ('fraud_blocked', 'Fraud blocked')], default='created', max_length=30),
        ),
    ]
