# Generated by Django 5.2.17 on 2026-08-09 08:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def preserve_payment_fees(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    TransactionFee = apps.get_model("payments", "TransactionFee")
    for payment in Payment.objects.all().iterator():
        rate = Decimal("0.0000")
        if payment.amount:
            rate = (payment.fee_amount * Decimal("100") / payment.amount).quantize(
                Decimal("0.0001")
            )
        net_amount = payment.amount
        if payment.fee_bearer == "merchant":
            net_amount = payment.amount - payment.fee_amount - payment.tax_amount
        payment.fee_percentage = rate
        payment.fee_source = "LEGACY"
        payment.verification_status_at_transaction = "PARTIAL"
        payment.fee_calculated_at = payment.created_at
        payment.save(
            update_fields=[
                "fee_percentage",
                "fee_source",
                "verification_status_at_transaction",
                "fee_calculated_at",
            ]
        )
        TransactionFee.objects.get_or_create(
            transaction=payment,
            defaults={
                "gross_amount": payment.amount,
                "fee_percentage": rate,
                "fee_amount": payment.fee_amount,
                "net_amount": net_amount,
                "fee_source": "LEGACY",
                "verification_status_at_transaction": "PARTIAL",
                "calculated_at": payment.created_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_merchantfeeoverride_verificationfeerule_and_more"),
        ("payments", "0003_payment_pricing_snapshot"),
        ("settlements", "0002_settlement_pricing_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="fee_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="fee_percentage",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="payment",
            name="fee_source",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="payment",
            name="merchant_fee_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="billing.merchantfeeoverride",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verification_fee_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="billing.verificationfeerule",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verification_status_at_transaction",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="TransactionFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("fee_percentage", models.DecimalField(decimal_places=4, max_digits=7)),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "fee_source",
                    models.CharField(
                        choices=[
                            ("VERIFICATION_PARTIAL", "Partial verification rule"),
                            ("VERIFICATION_VERIFIED", "Verified verification rule"),
                            ("MERCHANT_OVERRIDE", "Merchant override"),
                            ("LEGACY", "Migrated legacy fee"),
                        ],
                        max_length=30,
                    ),
                ),
                ("verification_status_at_transaction", models.CharField(max_length=20)),
                ("calculated_at", models.DateTimeField()),
                (
                    "merchant_fee_override",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_fees",
                        to="billing.merchantfeeoverride",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_fee",
                        to="payments.payment",
                    ),
                ),
                (
                    "verification_fee_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_fees",
                        to="billing.verificationfeerule",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["fee_source", "calculated_at"],
                        name="payments_tr_fee_sou_42a559_idx",
                    ),
                    models.Index(
                        fields=["verification_status_at_transaction"],
                        name="payments_tr_verific_988992_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(preserve_payment_fees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="payment",
            name="fee_bearer",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="pricing_plan_name",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="tax_amount",
        ),
    ]
