# Generated by Django 5.2.17 on 2026-08-09 08:45

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_merchantfeeoverride_verificationfeerule_and_more'),
        ('checkout', '0004_paymentsession_ck_session_amount_positive_and_more'),
        ('merchants', '0002_merchantactivity'),
        ('payments', '0004_remove_payment_fee_bearer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0), ('fee_amount__lt', models.F('amount'))), name='ck_payment_fee_valid'),
        ),
        migrations.AddConstraint(
            model_name='transactionfee',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0), ('fee_amount__gte', 0), ('net_amount__gt', 0)), name='ck_transaction_fee_amounts'),
        ),
        migrations.AddConstraint(
            model_name='transactionfee',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(models.F('fee_amount'), '+', models.F('net_amount')))), name='ck_transaction_fee_balanced'),
        ),
    ]
