# Generated by Django 5.2.17 on 2026-08-09 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_receipt_table_if_missing(apps, schema_editor):
    model = apps.get_model("payments", "PaymentReceipt")
    if model._meta.db_table not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_ck_payment_amount_positive_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=80, unique=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'db_table': 'receipts_electronicreceipt',
            },
            )],
        ),
        migrations.RunPython(create_receipt_table_if_missing, migrations.RunPython.noop),
    ]
