# Generated by Django 5.2.17 on 2026-08-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentreceipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
    ]
