# Generated by Django 5.2.17 on 2026-08-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_pricingplan_merchantplanassignment'),
        ('payments', '0007_delete_paymentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.merchantplanassignment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.pricingplan'),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='plan_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_fees', to='billing.merchantplanassignment'),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_fees', to='billing.pricingplan'),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='fee_source',
            field=models.CharField(choices=[('VERIFICATION_PARTIAL', 'Partial verification rule'), ('VERIFICATION_VERIFIED', 'Verified verification rule'), ('MERCHANT_OVERRIDE', 'Merchant override'), ('PRICING_PLAN', 'Pricing plan'), ('LEGACY', 'Migrated legacy fee')], max_length=30),
        ),
    ]
