# Generated by Django 5.2.17 on 2026-08-11 09:51

from django.db import migrations, models


def preserve_legacy_override_sources(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    TransactionFee = apps.get_model("payments", "TransactionFee")
    Payment.objects.filter(fee_source="MERCHANT_OVERRIDE").update(fee_source="LEGACY")
    TransactionFee.objects.filter(fee_source="MERCHANT_OVERRIDE").update(
        fee_source="LEGACY"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_plan_assignment_payment_pricing_plan_and_more'),
    ]

    operations = [
        migrations.RunPython(
            preserve_legacy_override_sources, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='payment',
            name='merchant_fee_override',
        ),
        migrations.RemoveField(
            model_name='transactionfee',
            name='merchant_fee_override',
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='fee_source',
            field=models.CharField(choices=[('VERIFICATION_PARTIAL', 'Partial verification rule'), ('VERIFICATION_VERIFIED', 'Verified verification rule'), ('PRICING_PLAN', 'Pricing plan'), ('LEGACY', 'Migrated legacy fee')], max_length=30),
        ),
    ]
