# Generated by Django 5.2.17 on 2026-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_payment_merchant_fee_override_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionfee',
            name='payments_tr_verific_988992_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_fee_rule',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_status_at_transaction',
        ),
        migrations.RemoveField(
            model_name='transactionfee',
            name='verification_fee_rule',
        ),
        migrations.RemoveField(
            model_name='transactionfee',
            name='verification_status_at_transaction',
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='fee_source',
            field=models.CharField(choices=[('PRICING_PLAN', 'Pricing plan'), ('PAY_AS_YOU_GO', 'Pay-as-you-go'), ('LEGACY', 'Migrated legacy fee')], max_length=30),
        ),
    ]
