# Generated by Django 5.2.17 on 2026-08-09 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('request_url', models.URLField()),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.JSONField(default=dict)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_history', to='webhooks.webhookdelivery')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='uq_webhook_delivery_attempt')],
            },
        ),
    ]
