# Generated by Django 5.2.17 on 2026-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookattempt',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='last_response_body',
            field=models.TextField(blank=True, help_text="Body the merchant's endpoint returned on the most recent attempt (truncated)."),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='last_response_headers',
            field=models.JSONField(blank=True, default=dict, help_text="Response headers from the merchant's endpoint on the most recent attempt."),
        ),
    ]
