# Generated by Django 5.2.17 on 2026-08-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevent',
            name='mode',
        ),
    ]
