# Generated by Django 5.2.17 on 2026-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_ck_payment_amount_positive_and_more'),
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_refund_amount_positive'),
        ),
    ]
