# Generated by Django 5.2.17 on 2026-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refund_ck_refund_amount_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(choices=[('order_cancelled', 'Order cancelled'), ('billing_error', 'Billing error'), ('delivery_failed', 'Delivery failed'), ('return', 'Returned merchandise'), ('fraud', 'Fraud'), ('technical', 'Technical incident'), ('dispute', 'Protection claim decision'), ('other', 'Other')], max_length=30),
        ),
    ]
