# Generated by Django 5.2.17 on 2026-08-12 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('under_review', 'Under review'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('merchant_reference', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('review', 'Manual review')], max_length=20)),
                ('confirmed_by', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(blank=True, choices=[('payer_secure_code', 'Secure delivery code'), ('verified_payer_alias', 'Verified payer alias'), ('merchant_evidence', 'Merchant evidence'), ('operations_review', 'Operations review')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='deliveries.delivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectionClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('mediation', 'Mediation'), ('arbitration', 'Arbitration'), ('won_customer', 'Resolved for payer'), ('won_merchant', 'Resolved for merchant'), ('closed', 'Closed')], default='open', max_length=30)),
                ('opened_by', models.CharField(blank=True, max_length=120)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protection_claims', to='payments.payment')),
            ],
            options={
                'db_table': 'disputes_dispute',
            },
        ),
        migrations.CreateModel(
            name='ProtectionClaimEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.ForeignKey(db_column='dispute_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.protectionclaim')),
            ],
            options={
                'db_table': 'disputes_disputeevent',
            },
        ),
        migrations.CreateModel(
            name='ProtectionClaimEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='protection-claims/%Y/%m/')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('claim', models.ForeignKey(db_column='dispute_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='deliveries.protectionclaim')),
            ],
            options={
                'db_table': 'disputes_disputeevidence',
            },
        ),
    ]
