# Generated by Django 5.2.17 on 2026-08-09 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_claim_tables_if_missing(apps, schema_editor):
    existing = set(schema_editor.connection.introspection.table_names())
    for name in ("ProtectionClaim", "ProtectionClaimEvent", "ProtectionClaimEvidence"):
        model = apps.get_model("deliveries", name)
        if model._meta.db_table not in existing:
            schema_editor.create_model(model)
            existing.add(model._meta.db_table)


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('payments', '0006_paymentreceipt'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='ProtectionClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('mediation', 'Mediation'), ('arbitration', 'Arbitration'), ('won_customer', 'Resolved for payer'), ('won_merchant', 'Resolved for merchant'), ('closed', 'Closed')], default='open', max_length=30)),
                ('opened_by', models.CharField(blank=True, max_length=120)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protection_claims', to='payments.payment')),
            ],
            options={
                'db_table': 'disputes_dispute',
            },
        ),
        migrations.CreateModel(
            name='ProtectionClaimEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.ForeignKey(db_column='dispute_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.protectionclaim')),
            ],
            options={
                'db_table': 'disputes_disputeevent',
            },
        ),
        migrations.CreateModel(
            name='ProtectionClaimEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='protection-claims/%Y/%m/')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('claim', models.ForeignKey(db_column='dispute_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='deliveries.protectionclaim')),
            ],
            options={
                'db_table': 'disputes_disputeevidence',
            },
        ),
            ],
        ),
        migrations.RunPython(create_claim_tables_if_missing, migrations.RunPython.noop),
    ]
