# Generated by Django 5.2.17 on 2026-09-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='method',
            field=models.CharField(blank=True, choices=[('payer_secure_code', 'Secure delivery code'), ('verified_payer_alias', 'Verified payer alias'), ('merchant_evidence', 'Merchant evidence'), ('operations_review', 'Operations review'), ('instant_settlement', 'Instant settlement (no confirmation)')], max_length=40),
        ),
    ]
