# Generated by Django 5.2.17 on 2026-08-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_protectionclaim_protectionclaimevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='method',
            field=models.CharField(blank=True, choices=[('payer_secure_code', 'Secure delivery code'), ('verified_payer_alias', 'Verified payer alias'), ('merchant_evidence', 'Merchant evidence'), ('operations_review', 'Operations review')], max_length=40),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('under_review', 'Under review'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='decision',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('review', 'Manual review')], max_length=20),
        ),
    ]
