# Generated by Django 5.2.17 on 2026-08-12 18:48

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField()),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='open', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('merchant_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('beneficiary_alias', models.CharField(blank=True, max_length=160)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='merchants.merchant')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='payments.payment')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='settlements.settlementbatch')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0), ('merchant_fee__gte', 0), ('refund_amount__gte', 0), ('net_amount__gte', 0)), name='ck_settlement_amounts_valid'), models.CheckConstraint(condition=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('merchant_fee'), '+', models.F('refund_amount')), '+', models.F('net_amount')))), name='ck_settlement_balanced')],
            },
        ),
    ]
