# Generated by Django 5.2.17 on 2026-08-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_remove_payment_fee_bearer_and_more"),
        ("settlements", "0002_settlement_pricing_breakdown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settlement",
            name="collected_amount",
        ),
        migrations.RemoveField(
            model_name="settlement",
            name="fee_bearer",
        ),
        migrations.RemoveField(
            model_name="settlement",
            name="platform_fee_amount",
        ),
        migrations.RemoveField(
            model_name="settlement",
            name="platform_fee_tax_amount",
        ),
        migrations.RemoveField(
            model_name="settlement",
            name="tax_amount",
        ),
    ]
