# Generated by Django 5.2.17 on 2026-08-09 08:45

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchantactivity'),
        ('payments', '0005_payment_ck_payment_amount_positive_and_more'),
        ('settlements', '0003_remove_settlement_fee_bearer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0), ('merchant_fee__gte', 0), ('refund_amount__gte', 0), ('net_amount__gte', 0)), name='ck_settlement_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('merchant_fee'), '+', models.F('refund_amount')), '+', models.F('net_amount')))), name='ck_settlement_balanced'),
        ),
    ]
