# Generated by Django 5.2.17 on 2026-08-08 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiduciaryAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=120)),
                ("account_name", models.CharField(blank=True, max_length=180)),
                ("currency", models.CharField(default="BIF", max_length=3)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("account_number", "currency")},
            },
        ),
        migrations.CreateModel(
            name="FiduciaryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("customer_funds", "Customer funds"),
                            ("release", "Release"),
                            ("refund", "Refund"),
                            ("fee", "Fee"),
                            ("tax", "Tax"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="customer_funds",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("reference", models.CharField(max_length=120)),
                ("narrative", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="fiduciary.fiduciaryaccount",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiduciary_entries",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FundHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("delivery_pending", "Delivery pending"),
                            ("delivery_confirmed", "Delivery confirmed"),
                            ("disputed", "Disputed"),
                            ("release_pending", "Release pending"),
                            ("released", "Released"),
                            ("refund_pending", "Refund pending"),
                            ("refunded", "Refunded"),
                            ("frozen", "Frozen"),
                        ],
                        default="held",
                        max_length=30,
                    ),
                ),
                ("held_at", models.DateTimeField(auto_now_add=True)),
                ("release_eligible_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("international", models.BooleanField(default=False)),
                ("freeze_reason", models.CharField(blank=True, max_length=255)),
                (
                    "fiduciary_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds",
                        to="fiduciary.fiduciaryaccount",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fund_hold",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
