# Generated by Django 5.2.17 on 2026-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0001_initial'),
        ('payments', '0004_remove_payment_fee_bearer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fiduciaryentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_fiduciary_entry_positive'),
        ),
        migrations.AddConstraint(
            model_name='fiduciaryentry',
            constraint=models.UniqueConstraint(fields=('payment', 'kind', 'reference'), name='uq_fiduciary_payment_kind_reference'),
        ),
        migrations.AddConstraint(
            model_name='fundhold',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_fund_hold_amount_positive'),
        ),
    ]
