# Generated by Django 5.2.17 on 2026-08-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiduciary', '0002_fiduciaryentry_ck_fiduciary_entry_positive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiduciaryaccount',
            options={'verbose_name': 'AmatoPay fiduciary account', 'verbose_name_plural': 'AmatoPay fiduciary account'},
        ),
        migrations.AlterUniqueTogether(
            name='fiduciaryaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fiduciaryaccount',
            name='alias_type',
            field=models.CharField(default='MOBILE', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='fiduciaryaccount',
            name='creditor_alias',
            field=models.CharField(default='', editable=False, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name='fiduciaryaccount',
            name='raw_verification',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='fiduciaryaccount',
            name='singleton_key',
            field=models.CharField(default='AMATOPAY', editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='fiduciaryaccount',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fiduciaryaccount',
            name='account_number',
            field=models.CharField(default='', editable=False, max_length=120, unique=True),
        ),
    ]
